Ct live athlinks changes for Event and Series
athlinks/rdf-ontology pull request #10
Opened 2017-03-31 21:04 UTC by LMayhew

2017-03-31 21:10 UTC, Astn requested changes
Please submit the whitespace changes as another merge request. Mixing document formatting with other changes makes reviews a PITA.

2017-04-03 20:50 UTC, Astn requested changes

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
Whats distinct about athlinks:elevationType vs athlinks:elevation? They both have the same label and description.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
I think athlinks:elevationGrade would be cleaner than elvationGradeType.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
There is already an athlinks:altitude property. I don't think we need 2.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
How about athlinks:distance instead of athlinks:distanceUnit.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range xsd:int.
This should at least have a range of Person or Organization. The name should likely be createdBy..And at that point.. We may be better off just using: http://schema.org/creator.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
Why not just include a line return in schema:streetAddress? Another property is pretty heavy when a \n could suffice.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
>    rdfs:range [ a xsd:string ;
Missing label.

2017-04-03 20:50 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:comment "Denotes who has access to see an object";
missing label

2017-04-04 02:59 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
OK

2017-04-04 03:06 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range xsd:int.
I like this.

2017-04-04 03:06 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:comment "Denotes who has access to see an object";
not my addition, only the semicolon... no idea what this is

2017-04-04 03:07 UTC, LMayhew commented on athlinks-schema.ttl
>    rdfs:range [ a xsd:string ;
same here...

2017-04-04 03:07 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
There are 2 address fields in both CTL and ATh.  There is already a streetAddress, but there needs to be a streetAddress2.

2017-04-04 03:11 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
No, this is an actual unit, my bad, needs to be a string.

2017-04-04 03:12 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
Not gonna fight you on this.  They probably dont use it anyway...

2017-04-04 14:58 UTC, warrencj commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
This can be handled in the mapping jobs (if street 2 exists, add it to street with \n)

2017-04-04 15:23 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:QuantitiveValue.
simile

2017-04-04 15:27 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
ok

2017-04-04 16:37 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:comment "Denotes who has access to see an object";
fixed

2017-04-07 15:36 UTC, Astn requested changes

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
rdfs:range should be schema:QuantitiveValue.
Should be renamed to just Distance. Not distance unit.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:Text.
Don't need this property yet. Please remove.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:range schema:creator.
We don't need this property. schema:creator does the same thing.
Additionally. rdfs:range schema:creator is incorrect as schema:creator is a property.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:label "The default recurrence of a certain scheduling item";
Changing comment to label is incorrect.
Please add a label without removing the comment.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:label "Denotes who has access to see an object" ;
Having the rdfs:label be the same as the comment is incorrect and lazy.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:label "ID of User Who Created Race";
Label is wrong. Don't duplicate the comment and store it in label. This is a public data model it needs to be good quality.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:label "Distance Unit to Display";
Label and comment are not the same thing.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:domain schema:Landform;
Label and comment should not be the same.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:comment "Altitude";
Label and comment should not be the same.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:comment "Elevation Grade";
Label and comment should not be the same.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:comment "Default Distance Unit";
Label and comment should not be the same.

2017-04-07 15:36 UTC, Astn commented on athlinks-schema.ttl
> +  rdfs:comment "Elevation";
Label and comment should not be the same.

2017-04-07 21:48 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:label "Denotes who has access to see an object" ;
Didnt do this.
Will try to fix.

2017-04-07 21:48 UTC, LMayhew commented on athlinks-schema.ttl
> +  rdfs:label "The default recurrence of a certain scheduling item";
Didnt do this.
Will try to fix.

2017-04-12 13:39 UTC, merged